sys(#err_nue_sigk)<
  @error = ERR_NUE_SIG
>

sys(#err_nue_sigbark)<
  @error = ERR_NUE_SIGBAR
>

sys(#err_numu_sigk)<
  @error = ERR_NUMU_SIG
>

sys(#err_numu_sigbark)<
  @error = ERR_NUMU_SIGBAR
>

sys(#err_numu_bgk)<
  @error = ERR_NUMU_BG
>

sys(#err_numu_bgbark)<
  @error = ERR_NUMU_BG
>

sys(#err_nue_bgk)<
  @error = ERR_NUE_BG
>

sys(#err_nutau_bgk)<
  @error = ERR_NUTAU_BG
>

sys(#err_nutau_bgbark)<
  @error = ERR_NUTAU_BG
>

sys(#err_nue_bgbark)<
  @error = ERR_NUE_BGBAR
>

sys(#err_nc_bgdisk)<
  @error = ERR_NC_BGDIS
>

sys(#err_nc_bgdisbark)<
  @error = ERR_NC_BGDIS
>


sys(#err_nue_sigpi)<
  @error = ERR_NUE_SIG
>

sys(#err_nue_sigbarpi)<
  @error = ERR_NUE_SIGBAR
>

sys(#err_numu_sigpi)<
  @error = ERR_NUMU_SIG
>

sys(#err_numu_sigbarpi)<
  @error = ERR_NUMU_SIGBAR
>

sys(#err_numu_bgpi)<
  @error = ERR_NUMU_BG
>

sys(#err_numu_bgbarpi)<
  @error = ERR_NUMU_BG
>

sys(#err_nue_bgpi)<
  @error = ERR_NUE_BG
>

sys(#err_nutau_bgpi)<
  @error = ERR_NUTAU_BG
>

sys(#err_nutau_bgbarpi)<
  @error = ERR_NUTAU_BG
>

sys(#err_nue_bgbarpi)<
  @error = ERR_NUE_BGBAR
>

sys(#err_nc_bgdispi)<
  @error = ERR_NC_BGDIS
>

sys(#err_nc_bgdisbarpi)<
  @error = ERR_NC_BGDIS
>

sys(#err_nue_sigD)<
  @error = ERR_NUE_SIG
>

sys(#err_nue_sigbarD)<
  @error = ERR_NUE_SIGBAR
>

sys(#err_numu_sigD)<
  @error = ERR_NUMU_SIG
>

sys(#err_numu_sigbarD)<
  @error = ERR_NUMU_SIGBAR
>

sys(#err_numu_bgD)<
  @error = ERR_NUMU_BG
>

sys(#err_numu_bgbarD)<
  @error = ERR_NUMU_BG
>

sys(#err_nue_bgD)<
  @error = ERR_NUE_BG
>

sys(#err_nutau_bgD)<
  @error = ERR_NUTAU_BG
>

sys(#err_nutau_bgbarD)<
  @error = ERR_NUTAU_BG
>

sys(#err_nue_bgbarD)<
  @error = ERR_NUE_BGBAR
>

sys(#err_nc_bgdisD)<
  @error = ERR_NC_BGDIS
>

sys(#err_nc_bgdisbarD)<
  @error = ERR_NC_BGDIS
>

sys(#err_nue_sigDs)<
  @error = ERR_NUE_SIG
>

sys(#err_nue_sigbarDs)<
  @error = ERR_NUE_SIGBAR
>

sys(#err_numu_sigDs)<
  @error = ERR_NUMU_SIG
>

sys(#err_numu_sigbarDs)<
  @error = ERR_NUMU_SIGBAR
>

sys(#err_numu_bgDs)<
  @error = ERR_NUMU_BG
>

sys(#err_numu_bgbarDs)<
  @error = ERR_NUMU_BG
>

sys(#err_nue_bgDs)<
  @error = ERR_NUE_BG
>

sys(#err_nutau_bgDs)<
  @error = ERR_NUTAU_BG
>

sys(#err_nutau_bgbarDs)<
  @error = ERR_NUTAU_BG
>

sys(#err_nue_bgbarDs)<
  @error = ERR_NUE_BGBAR
>

sys(#err_nc_bgdisDs)<
  @error = ERR_NC_BGDIS
>

sys(#err_nc_bgdisbarDs)<
  @error = ERR_NC_BGDIS
>

sys(#err_nue_sig)<
  @error = ERR_NUE_SIG
>

sys(#err_nue_sigbar)<
  @error = ERR_NUE_SIGBAR
>

sys(#err_numu_sig)<
  @error = ERR_NUMU_SIG
>

sys(#err_numu_sigbar)<
  @error = ERR_NUMU_SIGBAR
>

sys(#err_numu_bg)<
  @error = ERR_NUMU_BG
>

sys(#err_numu_bgbar)<
  @error = ERR_NUMU_BG
>

sys(#err_nue_bg)<
  @error = ERR_NUE_BG
>

sys(#err_nutau_bg)<
  @error = ERR_NUTAU_BG
>

sys(#err_nutau_bgbar)<
  @error = ERR_NUTAU_BG
>

sys(#err_nue_bgbar)<
  @error = ERR_NUE_BGBAR
>

sys(#err_nc_bgdis)<
  @error = ERR_NC_BGDIS
>

sys(#err_nc_bgdisbar)<
  @error = ERR_NC_BGDIS
>
